spring:
  application:
    name: ms-register
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  servlet:
    context-path: /api/v1
  port: 8888

api:
  sunat: https://api.apis.net.pe/v2/sunat/
  reniec: https://api.apis.net.pe/v2/reniec/

token:
  api: ${TOKEN_API}

time:
  expiration:
      info: 5

logging:
  level:
    org:
      springframework:
        data:
          redis: DEBUG
        cache: DEBUG